### ISSUE TITLE
Fix broken inspec test

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2042]
This is blocking PRs from getting reviewed properly and merged. Affected:

* https://github.com/ansible/molecule/pull/2034
* https://github.com/ansible/molecule/pull/2033
* https://github.com/ansible/molecule/pull/2036

I cannot reproduce this locally. I ran:

```
$ tox -e py37-ansible27-functional -- -v -k test_command_init_role_inspec -p no:warning
```

Log is (not useful at all ... another case against `sh`?):

From https://travis-ci.com/ansible/molecule/jobs/199661714#L451.
```console
=================================== FAILURES ===================================
________________________ test_command_init_role_inspec _________________________
temp_dir = local('/tmp/pytest-of-travis/pytest-0/test_command_init_role_inspec0/SVPPY')
    @needs_inspec
    @needs_rubocop
    def test_command_init_role_inspec(temp_dir):
        role_directory = os.path.join(temp_dir.strpath, 'test-init')
        options = {
            'role_name': 'test-init',
            'verifier_name': 'inspec',
        }
        cmd = sh.molecule.bake('init', 'role', **options)
        pytest.helpers.run_command(cmd)
        pytest.helpers.metadata_lint_update(role_directory)
    
        with change_dir_to(role_directory):
>           sh.molecule('test')
/home/travis/build/ansible/molecule/test/functional/docker/test_scenarios.py:104: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/travis/build/ansible/molecule/.tox/ansible27-functional/lib/python3.7/site-packages/sh.py:1427: in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
/home/travis/build/ansible/molecule/.tox/ansible27-functional/lib/python3.7/site-packages/sh.py:774: in __init__
    self.wait()
/home/travis/build/ansible/molecule/.tox/ansible27-functional/lib/python3.7/site-packages/sh.py:792: in wait
    self.handle_command_exit_code(exit_code)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = --> Validating schema /tmp/pytest-of-travis/pytest-0/test_command_init_role_inspec0/SVPPY/test-init/molecule/defa...changed=1    unreachable=0    failed=0
    
--> Pruning extra files from scenario ephemeral directory
code = 1
    def handle_command_exit_code(self, code):
        """ here we determine if we had an exception, or an error code that we
        weren't expecting to see.  if we did, we create and raise an exception
        """
        ca = self.call_args
        exc_class = get_exc_exit_code_would_raise(code, ca["ok_code"],
                ca["piped"])
        if exc_class:
            exc = exc_class(self.ran, self.process.stdout, self.process.stderr,
                    ca["truncate_exc"])
>           raise exc
E           sh.ErrorReturnCode_1: 
E           
E             RAN: /home/travis/build/ansible/molecule/.tox/ansible27-functional/bin/molecule test
E           
E             STDOUT:
E           --> Validating schema /tmp/pytest-of-travis/pytest-0/test_command_init_role_inspec0/SVPPY/test-init/molecule/default/molecule.yml.
E           Validation completed successfully.
E           --> Test matrix
E               
E           └── default
E               ├── lint
E               ├── dependency
E               ├── cleanup
E               ├── destroy
E               ├── syntax
E               ├── create
E               ├── prepare
E               ├── converge
E               ├── idempotence
E               ├── side_effect
E               ├── verify
E               ├── cleanup
E               └── destroy
E               
E           --> Scenario: 'default'
E           --> Action: 'lint'
E           --> Executing Yamllint on files found in /tmp/pytest-of-travis/pytest-0/test_command_init_role_inspec0/SVPPY/test-init/...
E           Lint completed successf... (1530 more, please see e.stdout)
E           
E             STDERR:
/home/travis/build/ansible/molecule/.tox/ansible27-functional/lib/python3.7/site-packages/sh.py:815: ErrorReturnCode_1
----------------------------- Captured stdout call -----------------------------
    --> Initializing new role test-init...
    Initialized role in /tmp/pytest-of-travis/pytest-0/test_command_init_role_inspec0/SVPPY/test-init successfully.
```

**Comment by webknjaz** [comment]
It looks like `molecule test` returned status code 1 but I have no idea why.

**Comment by seandst** [comment]
After upgrading my local install of inspec from 3.6.6 to 4.3.2, I'm able to reproduce this with the same (lack of) error seen in travis. Digging deeper now...

**Comment by seandst** [comment]
Downgrading to 3.6 to see if it's a matter of pinning inspec or not revealed that it was actually rubocop raising the error. :)

https://github.com/rubocop-hq/rubocop/commit/80bc82801489ca6fc637afe6078e2b2e9b7451e4#diff-fd50647d8291ed0994bf3f0ba3162662 set the rubocop cop in question to be always enforced with the most recent rubocop release, 0.69. Here's the error in the pytest logs after disabling exception truncation in `sh` for test runs:

```
    --> Executing RuboCop on files found in /tmp/pytest-of-semyers/pytest-10/test_command_init_role_inspec0/PNOOM/test-init/molecule/default/tests/...                                                                                         
        Inspecting 1 file                                                                                                                                                                                                                      
        C                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
        Offenses:                                                                                                                                                                                                                              
                                                                                                                                                                                                                                               
        molecule/default/tests/test_default.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.                                                                                                  
        # Molecule managed                                                                                                                                                                                                                     
        ^                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
        1 file inspected, 1 offense detected                                                                                                                                                                                                   
    An error occurred during the test sequence action: 'lint'. Cleaning up.                                   
```

Both the fix to this lint error and the related fix to prevent truncating exception strings are up in PR #2045.
